### ISSUE TITLE
Stats issue between mods.

### ISSUE THREAD

**Issue by border999** [YaibaToKen/Armory-Expansion#21]
https://github.com/ExtraMeteorP/Extra-Botany/issues/38

**Comment by border999** [comment]
https://paste.dimdev.org/urayifedam.mccrash

**Comment by YaibaToKen** [comment]
That definitely should not be happening. You can disable the material in the config file, meanwhile I'll look into pushing a fix.

**Comment by border999** [comment]
weird thing is that I actually can't find that material in the config.

**Comment by border999** [comment]
I mean, I'm looking for Oricalcum and the closest thing I find is Oricalcos.

**Comment by border999** [comment]
I'll try disabling it and seeing if it helps.

**Comment by YaibaToKen** [comment]
The config will use whatever name was assigned to the material by the first mod when registering it. In fact, I'm not even sure how I'm loading before ExtraBotany since I set my mod to load dead last. After all, the purpose of my mod is to fill in gaps left by other mods' TiC and ConArm integration.
Also, technically speaking, this crash isn't on my side, the creator of ExtraBotany should check if the material exists and if the stats are already defined before attempting to define them. He can also set his mod to load before mine, since mine will ignore any material with ConArm stats.

**Comment by border999** [comment]
I've made a similar suggestion to him. And I'm also curious why this started happening, because these mods were all working together up until a few days ago.

**Comment by YaibaToKen** [comment]
As you can check, Armory Expansion hasn't been updated since October 9th, 2018. It could be due to an update of the dependencies but my best bet would be something changed in ExtraBotany.

Anyway, for now, I would say remove Armory Expansion, launch the profile, switch the config option for the ExtraBotany ConArm compat off, add Armory Expansion again.
Or disable the needed materials in Armory Expansion's config file.

**Comment by border999** [comment]
will attempt

**Comment by border999** [comment]
https://pastebin.com/EBEKmdry
Alright man, this is really starting to look like the tinker's API is messing up. Because I'm getting the same issue from Pewter now that I pulled expansion out.

**Comment by YaibaToKen** [comment]
Two things, yes, TiC API should definitely not simply crash when someone tries to add a material that already exists, but, seeing as this is a known issue, mod authors should simply check if the material exists and only register if it doesn't.
