### ISSUE TITLE
[Bug] Missing botania materials

### ISSUE THREAD

**Issue by liny-fox** [YaibaToKen/Armory-Expansion#36]
In version 1.1.10c botania materials are not detected and registered automatically. Tested with beta 1.9 as well (would have tested against 1.8 as well, but that keep crashing on startup and being an outdated version, i didnt look into the crash), and they dont show up in that either. Im wondering if its related to the 1.8 redo with adding JSON support for defining new materials and maybe botania was overlooked or got broken in that refactoring. (Configs between testing 1.1.7b and 1.9 were not wiped so if anything, it should have been able to pull old values into the new system, but didnt)

**Comment by YaibaToKen** [comment]
I recall my Botania suport relying on existing TiC support. Don't recall if the TiC support was added by Botania itself or by a Botania add-on

**Comment by liny-fox** [comment]
But why would it work fine with 1.1.7b but not newer then?

**Comment by YaibaToKen** [comment]
probably because I screwed up something ^^'' I was just trying to confirm where the TiC support came from.

**Comment by liny-fox** [comment]
Ah, just you talking out loud in the comment.

**Comment by YaibaToKen** [comment]
sort of, I'm not entirely support where the base TiC support is added so I'll have to look into it first. It's a bit weird that only botania support broke though

**Comment by pupnewfster** [comment]
Similar to this when updating from 1.1.5 to 1.1.10 (haven't had a chance to test the in between versions), it seems support for dark matter and red matter from projecte (support added by plustic) broke. (In addition to the plustic botania materials), so maybe something got broken with the compat between armory expansion and plustic?

**Comment by YaibaToKen** [comment]
I'll be sure to test it out. PlusTiC and Botania, right?

**Comment by pupnewfster** [comment]
> I'll be sure to test it out. PlusTiC and Botania, right?

Ya PlusTiC and Botania, has them missing including PlusTiC's alloy of Mirion. PlusTiC + ProjectE should also have dark matter and red matter added, however that also seems to be missing now (at least in terms of what armory expansion adds)

**Comment by pupnewfster** [comment]
Ok @YaibaToKen I looked into it a bit and I *think* I know what broke and why. From what I can tell this commit https://github.com/YaibaToKen/Armory-Expansion/commit/c1ea7c54db633b3cf365bf83c54e03a1884f9da8 changed your looping over `TinkerRegistry.getAllMaterials()` from the item register event `RegistryEvent.Register<Item>` to preinit `FMLPreInitializationEvent`. From what I can tell for PlusTiC materials, they do not register stats/what part they are for until the item register event, [for example their botania module](https://github.com/Landmaster/PlusTiC/blob/1.12/src/main/java/landmaster/plustic/modules/ModuleBotania.java#L154). (Not quite sure if they register the fact the material exists at all before then or not.)

I am not quite sure how your system works so I don't know if things would directly break by just moving it (and am thus not just making a PR), but I believe this should be enough information so that you can fix it *relatively* easily. (Though I still would recommend double checking to make sure it is fixed before releasing an update as I did not test the change and am only pretty sure that is what is wrong.)

**Comment by YaibaToKen** [comment]
I consulted with everyone I knew about TiC integration phases and afaik I'm currently using the proper phases for registering stuff. It does seem, however, that it's just a matter of making sure I register my stats at a later phase, so I'll give a try asap and will get back to all of you on that.

**Comment by YaibaToKen** [comment]
A fix is available in `Armory Expansion WebClient Beta2`.
Will close this when the fix makes it to master.

**Comment by liny-fox** [comment]
This seems to now be broken again in 1.3.0 but works in 1.2.5 with the issue of #44 being present.

**Comment by liny-fox** [comment]
As a side effect of having ran version 1.3.0, it wiped all botania related modifiers and traits from all armor that was equipped causing me to have to use ftb-util's built in NBT editor to re-add them. Luckily I was the only one affected by this and only two armor pieces were broken,

**Comment by YaibaToKen** [comment]
For the moment I'd recommend making a copy of your config files before upgrading the mod ^^''

**Comment by YaibaToKen** [comment]
The missing materials are fixed in dev, branch material-partial-disable, I'll look into the missing colors asap.
