### ISSUE TITLE
[Bug] 1.3.0 configs disable a lot of armor types by default

### ISSUE THREAD

**Issue by katubug** [YaibaToKen/Armory-Expansion#48]
Hello there! After the most recent update to 1.3.0, my players and I noticed that all our armor containing Amethyst from BoP turned white, from magenta. And upon searching JEI to see if the color changed, Amethyst parts are gone.

I checked the config files and found that the amethyst options, as well as a bunch of others, were by default set to "false." I'm not sure if this is intended or not, but in my opinion it would be better to have everything enabled "out of the box" to avoid confusion, and let people disable them if desired. Rather than to have them all on an "opt in" basis.

In any case, thank you very much for the great mod, and the intricate config options. As a modpack maker, I love that you added more ability for us to enable or disable armor types. Thanks again!

**Comment by YaibaToKen** [comment]
Thanks for the report, that seems to be a bug of the new config system ^^'' the system should only set options to false if the materials doesn't have that part by default, unfortunately it isn't fully working and I actually had no idea about that bug.

**Comment by katubug** [comment]
Ah, okay! Thank you for the quick response! I hope it's not too much trouble to fix.

In the meantime, I'm going to edit the configs manually, but I have a question: if something is castable, should it also be craftable? Or is it a choice between either being castable or being craftable?

And since all the "traits" are empty, do I have to manually type in the traits they have in order for them to work? How does the syntax for that work?

Thanks so much!

**Comment by katubug** [comment]
Upon further review, it seems that any changes I make to conarm-config.json's

>       "armorOptions": {
>       "enableArmor": 
>       "enableCore": 
>       "enablePlates": 
>       "enableTrim": 

or the Tool/Weapon options do not save, even if they match the conarm-materials.json.

**Comment by YaibaToKen** [comment]
Yeah, that's the major bug I need to fix atm, been working on it the last couple of days but life has been hectic. As for the traits, I've yet to add traits to most materials, but you can add any existing trait to any material part. You can check iceandfire-materials.json for an example.
I'm hoping to have it fixed till the end of the week 😅
As for crafting and casting, crafting is fully working while casting registers a fluid for the material but isn't fully working with Tinker's (yet). This isn't a problem for the materials in the ConArm file as those will already have a fluid if they are castable by default (since I only add stats for the armor parts for those materials).
Mind you, you can change them to also be craftable if you wish.

**Comment by YaibaToKen** [comment]
The mod also generates a file named `traits.txt` that should contain all trait names in use by any TiC addon, generated at runtime.

**Comment by katubug** [comment]
Ah, gotcha! Thanks for the detailed explanation! Good luck on squashing the
bug, that's always a rough experience. Thanks again!

**Comment by LemADEC** [comment]
On a similar note, both versions 1.3.0 and "WebClient Beta3" are adding the following "Ice and Fire" materials even when the mod is missing:
- Desert Myrmex Chitin
- Jungle Myrmex Chitin
- Dragon Bone

**Comment by YaibaToKen** [comment]
@LemADEC thanks for bringing that up, could I bother you to make a new issue for it though? Makes it a lot easier to track.
